name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CMake configure
      run: cmake -B./build
    - name: Build
      run: cmake --build ./build
    - name: Install
      run: sudo cmake --install ./build
    - name: Run
      run: scpi_cli
